import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.Barcode128;
import com.itextpdf.text.pdf.Barcode39;
import com.itextpdf.text.pdf.PdfAction;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfDictionary;
import com.itextpdf.text.pdf.PdfName;
import com.itextpdf.text.pdf.PdfNumber;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import javax.swing.filechooser.FileFilter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractCellEditor;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
/*
* Class: GUI
* @author: Sean Bailey
* Date Created: 5/14/2012
* Date Modified: 5/18/2012
* Purpose: Contains all logic for the barcode scanner app. Bad practice but the app is so small it really
* doesn't make that much of a difference.
* 
*/
 
public class GUI extends javax.swing.JFrame {
    private static final int PACK_SIZE = 20;                //max number of elements that will fit on a label
    private static final String FILE_EXTENSION = ".lbl";    //default file extension for the data save files
    private int labelSize = PACK_SIZE;                      //number of rows the label input table contains
    private Stack longBarcodes = new Stack<Object>();       //*unused* intended for document rotation of long barcodes
    private static final String HINT_TEXT = "Invoice , PO, Customer";   //the 'hint' text that shows up on launch in the title field.
    private int serialCount = 0;
    private int boxCount = 1;
    GridBagConstraints constraints;
    ArrayList<String> serialEntries = new ArrayList<String>();
    boolean dataSaved = true;
    
    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        header_panel = new javax.swing.JPanel();
        labelTitle_lbl = new javax.swing.JLabel();
        label_title_tf = new javax.swing.JTextField();
        headerNumber_lbl = new javax.swing.JLabel();
        model_number_tf = new javax.swing.JTextField();
        unitsPerCase_lbl = new javax.swing.JLabel();
        unitsPerCase_tf = new javax.swing.JTextField();
        footer_panel = new javax.swing.JPanel();
        clear_btn = new javax.swing.JButton();
        printLabel_btn = new javax.swing.JButton();
        newLabel_btn = new javax.swing.JButton();
        open_btn = new javax.swing.JButton();
        display_panel = new javax.swing.JPanel();
        serial_lbl = new javax.swing.JLabel();
        serialEntry_tf = new javax.swing.JTextField();
        serialAdd_btn = new javax.swing.JButton();
        count_lbl = new javax.swing.JLabel();
        serialCount_lbl_data = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boxCount_lbl_data = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serialsTable = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        newLabel_menuItem = new javax.swing.JMenuItem();
        open_menuItem = new javax.swing.JMenuItem();
        print_menu_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Packing Label Creator v2.0");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(300, 600));
        setName("Hard drive packing label creator"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelTitle_lbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelTitle_lbl.setText("Title:");
        labelTitle_lbl.setToolTipText("Label Title: Invoice, PO, Customer");

        label_title_tf.setFont(new java.awt.Font("DialogInput", 0, 20)); // NOI18N
        label_title_tf.setText("Invoice, PO, Customer");
        label_title_tf.setToolTipText("Invoice, PO, Customer");
        label_title_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_title_tfMouseClicked(evt);
            }
        });
        label_title_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                label_title_tfKeyPressed(evt);
            }
        });

        headerNumber_lbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        headerNumber_lbl.setText("Model Number:");
        headerNumber_lbl.setToolTipText("Model number");

        model_number_tf.setFont(new java.awt.Font("DialogInput", 0, 20)); // NOI18N
        model_number_tf.setToolTipText("Model number");
        model_number_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                model_number_tfMouseClicked(evt);
            }
        });
        model_number_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                model_number_tfKeyPressed(evt);
            }
        });

        unitsPerCase_lbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        unitsPerCase_lbl.setText("Units per box:");
        unitsPerCase_lbl.setToolTipText("Max number of units in a box.");

        unitsPerCase_tf.setFont(new java.awt.Font("DialogInput", 0, 20)); // NOI18N
        unitsPerCase_tf.setText("20");
        unitsPerCase_tf.setToolTipText("Max number of units in a box.");
        unitsPerCase_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unitsPerCase_tfMouseClicked(evt);
            }
        });
        unitsPerCase_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                unitsPerCase_tfFocusLost(evt);
            }
        });
        unitsPerCase_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unitsPerCase_tfKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitsPerCase_tfKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                        .addComponent(labelTitle_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_title_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                    .addGroup(header_panelLayout.createSequentialGroup()
                        .addComponent(headerNumber_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model_number_tf))
                    .addGroup(header_panelLayout.createSequentialGroup()
                        .addComponent(unitsPerCase_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unitsPerCase_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_title_tf)
                    .addComponent(labelTitle_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerNumber_lbl)
                    .addComponent(model_number_tf))
                .addGap(8, 8, 8)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitsPerCase_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitsPerCase_lbl)))
        );

        header_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {label_title_tf, model_number_tf, unitsPerCase_tf});

        clear_btn.setText("clear serials");
        clear_btn.setToolTipText("Clear all serial numbers from the table.");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        printLabel_btn.setText("save & print");
        printLabel_btn.setToolTipText("Saves pdf and opens file");
        printLabel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLabel_btnActionPerformed(evt);
            }
        });

        newLabel_btn.setText("new label");
        newLabel_btn.setToolTipText("Clears all fields for a new label.");
        newLabel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLabel_btnActionPerformed(evt);
            }
        });

        open_btn.setText("open label");
        open_btn.setToolTipText("Opens a label file.");
        open_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footer_panelLayout = new javax.swing.GroupLayout(footer_panel);
        footer_panel.setLayout(footer_panelLayout);
        footer_panelLayout.setHorizontalGroup(
            footer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footer_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(open_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newLabel_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printLabel_btn)
                .addContainerGap())
        );
        footer_panelLayout.setVerticalGroup(
            footer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footer_panelLayout.createSequentialGroup()
                .addGroup(footer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(printLabel_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newLabel_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(open_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        serial_lbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        serial_lbl.setText("Serial #:");

        serialEntry_tf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        serialEntry_tf.setText("Click here and scan.");
        serialEntry_tf.setToolTipText("Scan serial numbers in here and press enter.");
        serialEntry_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serialEntry_tfMouseClicked(evt);
            }
        });
        serialEntry_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialEntry_tfActionPerformed(evt);
            }
        });
        serialEntry_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serialEntry_tfKeyPressed(evt);
            }
        });

        serialAdd_btn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        serialAdd_btn.setText("Add");
        serialAdd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialAdd_btnActionPerformed(evt);
            }
        });

        count_lbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        count_lbl.setText("Serial Count:");

        serialCount_lbl_data.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        serialCount_lbl_data.setText("0");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Box Count:");

        boxCount_lbl_data.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        boxCount_lbl_data.setText("0");

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        serialsTable.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        serialsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Serial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        serialsTable.setAutoscrolls(false);
        serialsTable.setColumnSelectionAllowed(true);
        serialsTable.getTableHeader().setReorderingAllowed(false);
        serialsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serialsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(serialsTable);
        serialsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        serialsTable.getColumnModel().getColumn(0).setMinWidth(50);
        serialsTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        serialsTable.getColumnModel().getColumn(0).setMaxWidth(50);

        javax.swing.GroupLayout display_panelLayout = new javax.swing.GroupLayout(display_panel);
        display_panel.setLayout(display_panelLayout);
        display_panelLayout.setHorizontalGroup(
            display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(display_panelLayout.createSequentialGroup()
                        .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(count_lbl)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxCount_lbl_data)
                            .addComponent(serialCount_lbl_data)))
                    .addGroup(display_panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(serial_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serialEntry_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serialAdd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        display_panelLayout.setVerticalGroup(
            display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(display_panelLayout.createSequentialGroup()
                        .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serial_lbl)
                            .addComponent(serialEntry_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serialAdd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(count_lbl)
                            .addComponent(serialCount_lbl_data))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(boxCount_lbl_data))
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)))
        );

        file_menu.setText("File");

        newLabel_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newLabel_menuItem.setText("New Label");
        newLabel_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLabel_menuItemActionPerformed(evt);
            }
        });
        file_menu.add(newLabel_menuItem);

        open_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open_menuItem.setText("Open");
        open_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_menuItemActionPerformed(evt);
            }
        });
        file_menu.add(open_menuItem);

        print_menu_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        print_menu_item.setText("Print");
        print_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_menu_itemActionPerformed(evt);
            }
        });
        file_menu.add(print_menu_item);

        menuBar.add(file_menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(footer_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(display_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Function: focusTf
     * Purpose: sets the focus on the label title text field on window load and every time 
     * new label is called and also repopulates the default 'hint' text
     */
    public void focusTf(){
        this.label_title_tf.requestFocusInWindow();
        this.label_title_tf.setText(HINT_TEXT);
        this.label_title_tf.selectAll();
    }
    
/*
 * Function: clear_btnActionPerformed
 * Purpose: clears the JTable that holds the serial numbers. One at a time, and sets the focus
 * back at the first row ready for input once again.
 * @param: actionEvent evt
 */
private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
    DefaultTableModel model = (DefaultTableModel)this.serialsTable.getModel();
    for(int i = model.getRowCount() - 1 ; i >= 0; i--){
        model.removeRow(i);
    }
    this.serialEntries = new ArrayList<String>();
    this.updateSerialCounter(-this.serialCount);
    this.boxCount = 0;
}//GEN-LAST:event_clear_btnActionPerformed

/*
 * Function: manipulatePdf
 * Purpose: *unused* Rotates the pdf by 90 degrees after writing; intended for use with
 * long barcode handling.
 * @param: String src: the source pdf file to rotate
 * @param: String dest: the destination pdf file to save rotation.
 */
 public void manipulatePdf(String src, String dest) throws IOException, DocumentException {
        PdfReader reader = new PdfReader(src);
        int n = reader.getNumberOfPages();
        int rot;
        PdfDictionary pageDict;
        for (int i = 1; i <= n; i++) {
            rot = reader.getPageRotation(i);
            pageDict = reader.getPageN(i);
            pageDict.put(PdfName.ROTATE, new PdfNumber(rot + 90));
        }
        PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(dest));
        stamper.close();
 }

 /*
  * Function: scaleBarcode
  * Purpose: creates a barcode image given a string. The image is scaled if the string length
  * is longer than 17 characters; which seems to be the max number of characters that fit on a 
  * 4x6 label.
  * @param: String code: the string you want to convert to a barcode image
  * @param: PdfWriter writer: reference to a writer which is needed to created the image
  * @returns: itext.text.Image image of the barcode
  */
 public com.itextpdf.text.Image scaleBarcode(String code, PdfWriter writer){
    Barcode39 code39 = new Barcode39();
    code39.setSize(6f);     //sets font size of text below the barcode
    code39.setBarHeight(8); //sets the height of the bars for the barcode
    code39.setX(1);         //sets the min width of the bars
    
    code39.setCode(code);   //binds the input string to the Barcode39 object's code
    PdfContentByte cb = writer.getDirectContent();  //required to create the image
    com.itextpdf.text.Image tehImage = code39.createImageWithBarcode(cb, null, null); //itext Image object of the barcode
    
    //image scaling logic; limited to 17 characters unscaled by 4x6. 37 characters max scalable 
    if(code.length() > 17){
        tehImage.scaleAbsoluteWidth(270);
    }
    return tehImage;
 }
 
 /*
  * Function: initTable
  * Purpose: Initializes the pdf table that holds the serial numbers. Is called for each 'page' 
  * of the pdf.
  * @param: int size - the number of columns in the table
  * @returns: PdfPTable with the given number of columns and column widths
  */
 public PdfPTable initTable(int size){
        PdfPTable table = new PdfPTable(size);  //creates table object and sets number of columns
       
        float dims [] = new float [2];          //the array to hold the column widths
        dims[0] = .2f;                          //hard coded first column width; item number
        dims[1] = 4f;                           //hard coded barcode column width
        table = new PdfPTable(dims);            //creates the table with the new column widths
        table.setWidthPercentage(100);          //sets the width of the table to the width of the page
        return table;
 }
  
  /*
  * Function: addHeader
  * Purpose: Adds the header of the label that contains label title, model number, and the case number.
  * @param: Document document - reference to the current document being written to.
  * @param: PdfWriter writer - reference to the current writer writing to the pdf.
  * @param: int caseNumber - the current 'box' the label is on
  * @param: int numberOfCases - the max number of 'boxes' 
  */
  public void addHeader(Document document, PdfWriter writer, int caseNumber, int numberOfCases) throws DocumentException{
        String title1 = this.label_title_tf.getText().toUpperCase();        //sends to uppercase in case conversion to barcode is needed
        String headerNumber = this.model_number_tf.getText().toUpperCase();
        
        //label title object
        Paragraph labelTitle;
          
        //scaling logic for the title to prevent wrapping and offsetting the number of elements on a label
        if(title1.length() < 32)
             labelTitle= new Paragraph(title1,new Font(FontFamily.COURIER,15));
        else if (title1.length() < 39){
            labelTitle= new Paragraph(title1,new Font(FontFamily.COURIER,12));
        } else if(title1.length() < 59) {
            labelTitle= new Paragraph(title1,new Font(FontFamily.COURIER,8));
        } else {
            labelTitle= new Paragraph(title1,new Font(FontFamily.COURIER,5));
        }
        
        //table object holding the title to hold the barcode
        PdfPTable titleTable = new PdfPTable(1);
        
        //sets table to the width of the page
        titleTable.setWidthPercentage(100f);
        
        labelTitle.setAlignment(Element.ALIGN_CENTER);
        
        //adds the label title to the document object
        document.add(labelTitle);
        
        //table object that holds header and case text
        PdfPTable table = new PdfPTable(new float[] {5f, 2f});
        table.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell();
        
        //Label Header Number
        Paragraph labelHeaderNumber = new Paragraph(headerNumber,new Font(FontFamily.HELVETICA,12));
        labelHeaderNumber.setAlignment(Element.ALIGN_LEFT);
        cell = new PdfPCell(labelHeaderNumber);
    
        cell.setBorder(0);  //remove cell border
        table.addCell(cell);//adds the title cell to the table object
        
        //object to hold current box of max boxes text
         Paragraph caseNumberLabel = new Paragraph("Box: " + caseNumber + " of " + numberOfCases,new Font(FontFamily.HELVETICA,12));
         
         //set text alignment to the right of the cell
         caseNumberLabel.setAlignment(Element.ALIGN_RIGHT);
         
         //puts the object text into a PdfPCell object
         cell = new PdfPCell(caseNumberLabel);
         cell.setBorder(0); //remove cell border
         table.addCell(cell);   //add the cell to the table object
        
        document.add(table);    //add table to the document 
        
        //paragraph object that holds 'Serial Numbers' label for the table
        Paragraph serials = new Paragraph("      Serial Numbers:", new Font(FontFamily.HELVETICA,8));
        
        //adds serial numbers label to the document
        document.add(serials);
    }
 
/*
* Function: findData()
* Purpose: checks to see if the serials number table object has any data in the table rows.
* @returns true - at the first non-null/empty value in the table
* @returns false - if it goes through the whole table and finds nothing.
*/
private boolean findData(){
    
     //else the table is empty and return false
     return true;
 }
 
 /*
 * Function: generateLongPDF
 * Purpose: *unused* Generates a pdf file that interchanges the height and width dimensions and then
 * calls the manipulatePDF function to rotate the file so that it prints in a landscape format.
 * @param int counter - the number of items that have already been printed to a label; default is 1
 */
 private void generateLongPDF(int counter){
     if(!(longBarcodes.size() <= 0)){
         try{
            Rectangle pageSize = new Rectangle(600,400);
            Document document = new Document(pageSize, 7.5f, 7.5f,0f,0f);
            // step 2
            PdfWriter writer;
            writer = PdfWriter.getInstance(document, new FileOutputStream("packingListLong.pdf"));
            
            document.open();
            
            PdfContentByte cb = writer.getDirectContent();
            document.add(new Paragraph("Hi"));
            //add title and header
            //addHeader(document,0,1);
        
            //set data table
            PdfPTable table = initTable(3);


            PdfPCell cell = new PdfPCell();
            cell.setFixedHeight(1f);
            cell.setPaddingTop(1f);
            
            for(int i = 0; i < longBarcodes.size(); i++, counter++){
                //add count
                cell = new PdfPCell(new Paragraph(""+counter, new Font(Font.FontFamily.HELVETICA, 6)));
                cell.setBorder(0);
                cell.setPaddingTop(1f);
                //cell.setPaddingBottom(6f);
                table.addCell(cell);
                
                //add barcode
                cell = new PdfPCell((Image)longBarcodes.pop());
                cell.setBorder(0);
                cell.setPaddingTop(1f);
                //cell.setPaddingBottom(0f);
                table.addCell(cell);
            }
            document.add(table);
            document.close();
         } catch (DocumentException de) {
             System.out.println(de);
         } catch (FileNotFoundException fnf) {
             System.out.println(fnf);
         }
     }
 }
 
 public HardDriveInvoice createHdInvoice(){
     String invoiceNumber = this.getInvoiceNumber();
     String model = this.getModel();
     Date date = new Date();
     ArrayList<String> serials = this.getSerials();
     
     return (new HardDriveInvoice(invoiceNumber, model, date, serials));
 }
 
 public String getInvoiceNumber(){
     return this.label_title_tf.getText();
 }
 
 public ArrayList<String> getSerials(){
     return this.serialEntries;
 }
 
 public String getModel(){
     return this.model_number_tf.getText();
 }
 
 /*
  * Function: saveDataText
  * Purpose: Saves the label data to a text file using the FILE_EXTENSION and as a csv file
  */
 private void saveDataText(){
     String fileName;       //stores FILE_EXTENSION name
     String fileNameCSV;    //stores CSV name
     fileName = resolveFileName(FILE_EXTENSION);    //resolves the path to the FILE_EXTENSION file
     fileNameCSV = resolveFileName(".csv");         //resolves the path to the csv file
     HardDriveInvoice hdInvoice = this.createHdInvoice();
     SerialFileManager sfm = new SerialFileManager();
     sfm.addToRepoFile(hdInvoice);
     
     BufferedWriter writer = null;
     BufferedWriter csvWriter = null;
             
     try{
         HardDriveInvoice hdi = this.createHdInvoice();
         if(hdi != null){
             writer = new BufferedWriter(new FileWriter(fileName));   //writer object that writes to the FILE_EXTENSION file
             hdi.writeToFile(writer);
             this.updateSavedState(true);
         }
        /*writer = new BufferedWriter(new FileWriter(fileName));   //writer object that writes to the FILE_EXTENSION file
        csvWriter = new BufferedWriter(new FileWriter(fileNameCSV)); //writer object that writes to the csv file
        writer.write("title: " + label_title_tf.getText());                          //write label title to the file
        csvWriter.write("title: " + label_title_tf.getText());  
        csvWriter.write(",");                                                        //put a comma for the csv
        
        writer.newLine();                                       //insert line break
        csvWriter.newLine();
        
        writer.write("header: " + model_number_tf.getText());  //write header/modelnumber to the file
        csvWriter.write("header: " + model_number_tf.getText());
        
        csvWriter.write(",");   //put comma for the csv
        
        writer.newLine();       //insert line break
        csvWriter.newLine();    
        csvWriter.write("Serials:");
        
        for(int i = 0; i < this.serialEntries.size(); i++){
            writer.write(this.serialEntries.get(i));
            writer.newLine();
            csvWriter.write(this.serialEntries.get(i)+",");
        }
        
        //loop to cycle through the serial numbers table data
       */
     } catch (FileNotFoundException fnf) {  //filenotfound thrown when directory is missing
         //try and recreate directory structure
         if(createFileDirectory()){ //if successful then call this function again
             saveDataText();
         } else {
             System.out.println("Unable to create file");   //if failure then give up and don't save
             return;
         }
         this.updateSavedState(false);
     } catch (IOException ioe) {    //thrown when writer objects
         System.out.println(ioe);
         this.updateSavedState(false);
     } finally {
         try {
             writer.close();
             //csvWriter.close();
         } catch (IOException ex) {
             Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
         }
         
     }
 }
 
 
 /*
  * Function: resolveFileName
  * Purpose: Resolves the path for a file to be saved by the program. Also handles the auto
  * filename incrementing.
  * @param: String fileType - the type of file that is being saved {PDF,LBL,CSV}
  * @returns: String fileName - the name as the absolute path to the file
  */
 private String resolveFileName(String fileType){
     String fileName;   //holds file name
     File dataFile;     //file object to test if file exists
     String location;   //location of the file
     String title = this.label_title_tf.getText();  //title of the file
     
     //if no file name provided then use 'untitled'
     if(title.trim() == null || title.trim().equals("")){
         title = "untitled";
     }
     
     //Block to determine where to save the file based on file extension
     if(fileType == ".pdf"){
         location = System.getProperty("user.home")+"\\Documents\\PackingLabels\\";
     } else if (fileType == ".lbl") {
         location = System.getProperty("user.home")+"\\Documents\\PackingLabels\\LabelFiles\\";
     } else if (fileType == ".csv"){
         location = System.getProperty("user.home")+"\\Documents\\PackingLabels\\LabelFiles\\csvs\\";
     } else {
         location = System.getProperty("user.home")+"\\Documents\\PackingLabels\\LabelFiles\\";
     }
     
     
     int i = 0; //file name increment counter
     do{        //loop until you have a unique file name
         if(i == 0){
             fileName = location + (title+fileType).trim();
         } else {
             fileName = location + (title + "["+i+"]"+fileType).trim();
         }
         dataFile = new File(fileName);
         i++;
     } while(dataFile.exists());    
     return fileName;
 }
 
 /*
  * Function: loadData
  * Purpose: loads the data from a selected .FILE_EXTENSION file or a .CSV file and populates the
  * application's serial numbers data table.
  * @param: String fileName - as the absolute path to the file that is to be loaded
  */
 private void loadData(String fileName){
        try {
            boolean isCSV = false;  //boolean value for checking if the file being read is a csv
            
            //check if the file is a .csv file if it is then set isCSV true
            if(fileName.contains(".csv"))
                isCSV = true;
            
            //Reader object that connects to the file to be loaded
            BufferedReader reader = new BufferedReader(new FileReader(fileName));
            
            String currentLine = reader.readLine(); //current line of the file being read
            
            int rowCount = 0;   //determines which row the data is going to populate
            while(currentLine != null) {    //loop through the file until you find no data
                
                //if you're at the max number of rows in the table, increment
                if(rowCount >= labelSize){
                    ;//increaseTableSize();
                }
                
                //if the current line contains 'title:' then it must be the title of the label
                if(currentLine.contains("title:")){
                    //parse the 'title:' from the line
                    String [] temp = currentLine.split(":");
                    
                    if(temp.length > 1){                       //if there's anything left after splitting then that's your title
                        String text = temp[1].trim();          //trim any whitespace from the title
                        if(isCSV){                             //if it's a csv file then remove the comma at the end
                            text = text.substring(0, text.length()-1);
                        }
                                                              //finally set the label title field text to what was parsed
                        this.label_title_tf.setText(text);
                    }
                } else if (currentLine.contains("header:")) { //else if it contains 'header:' then it must be the header/model number
                    //parse the 'header:' from the line
                    String [] temp = currentLine.split(":");    
                    
                    if(temp.length > 1){                    //if there's anything left after splitting then that's your header/modelnumber
                        String text = temp[1].trim();       //trim any whitespace
                        if(isCSV){                          //if it's a csv file then remove the comma at the end
                             text = text.substring(0, text.length()-1);
                        }
                        
                        //finally set the label title field text to what was parsed
                        this.model_number_tf.setText(text);
                    }
                } else {                                                    //else it must be a serial number line
                    String text = currentLine.trim();                       //trim the whitespace
                    if(isCSV){                                              //if it's a csv remove the comma at the end
                        text = text.substring(0, text.length()-1);
                    }
                    
                    rowCount++;                                             //increment the row count
                }
                currentLine = reader.readLine();
            }
            //check once more to see if more lines need be added to the input table
            if(rowCount >= labelSize){
                ;//increaseTableSize();
            }
        } catch (FileNotFoundException fnf) { //should never be thrown, but will occur if loading file disappears
            return;
        } catch (IOException ioe) { //thrown when the reader breaks
            return;
        }
 }
 
 private void updateInvoiceNumber(String invoiceNumber){
     this.label_title_tf.setText(invoiceNumber.trim());
 }
 
 private void updateModel(String model){
     this.model_number_tf.setText(model.trim());
 }
 
 private void updateSerialCount(String count){
     this.serialCount_lbl_data.setText(count.trim());
     //add catch for invalid number
     this.serialCount = Integer.parseInt(count.trim());
     this.checkNewBox();
 }
 
 private void loadLabel(String fileName){
     boolean isLBL = false;
     
     if(fileName.contains(".lbl")){
         BufferedReader br = null;
         try {
             isLBL = true;
               br = new BufferedReader(new FileReader(fileName));
              //first line is empty
              if(br.readLine() != null){
                 
                //second line is Invoice: <invoice number>
                  String readLine = "";
                  readLine = br.readLine();
                  String [] currentLine = readLine.split(":");
                  //add catch for length of current line
                  this.updateInvoiceNumber(currentLine[1]);
                    //third line is Model: <model #>
                  readLine = br.readLine();
                  currentLine = readLine.split(":");
                  this.updateModel(currentLine[1]);
                  
                  //fourth line is Date: MM/dd/yyyy HH:mm:ss
                  readLine = br.readLine();
                  
                  
                //fifth line is Qty: <qty>
                  readLine = br.readLine();
                  currentLine = readLine.split(":");
                  this.updateSerialCount(currentLine[1]);
                //fifth and beyond = entry#:serial
                  while((readLine = br.readLine()) != null){
                      currentLine = readLine.split(":");
                      this.addSerial(currentLine[0], currentLine[1]);
                  }
              }
         } catch (IOException ex) {
             Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ArrayIndexOutOfBoundsException aiobe){
             System.err.println("Out of bounds on an array...bad stuff");
         } finally {
             try {
                 br.close();
             } catch (IOException ex) {
                 System.err.println("Buffered reader failed to close");
             }
         }
     } else {
         System.err.println("Invalid label file!");
           JOptionPane.showMessageDialog(null,
                "Not a valid .lbl file.",
                "Invalid file type error",
                JOptionPane.ERROR_MESSAGE);
     }
     
     
 }
 
 /*
  * Function: createFileDirectory
  * Purpose: Generates the directory structure the application uses. Places a folder in the user's 'home'
  * directory called 'Documents' then the 'PackingLabels' directory where the pdf files are stored, then
  * the LabelFiles directory where the load data (FILE_EXTENSION) data is stored, and finally the csvs
  * directory where all csv copies of the data are stored. 
  * Function is 100% passive in that if will only create a directory if it doesn't exist.
  * @returns true - if directory structure was generated successfull
  * @returns false - if for whatever reason it failed...and it probably throws an exception that isn't handled
  */
 private boolean createFileDirectory(){
     return (new File(System.getProperty("user.home")+"\\Documents\\PackingLabels\\LabelFiles\\csvs")).mkdirs();
 }
 
 /*
  * Function: getTableSize
  * Purpose: Returns the number of data elements in the table, as rowCount simply returns the number of 
  * rows the serial numbers table object contains regardless of if they're populated or not.
  * @returns: int dataCount - the amount of non-null/empty data it found. 
  */
 private int getTableSize(){
     int dataCount = 0;
     
     return dataCount;
 }
 
 /*
  * Function: printLabel_btnActionPerformed
  * Purpose: Main save and print logic for the program. When the button is pressed the program checks
  * if the serial numbers table has any data, if not then it generates an error dialog and returns. If
  * data is found then it checks if there's a title, if not then it generates a dialog and returns. If
  * those two conditions are met then it starts creating the PDF file
  */
private void printLabel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLabel_btnActionPerformed
    try{
        if(!findData()){
            //custom title, error icon
            JOptionPane.showMessageDialog(null,
                "No barcodes to generate, don't waste a label!",
                "No data error",
                JOptionPane.ERROR_MESSAGE);
                this.updateSavedState(true);
            return;
        } else if (this.label_title_tf.getText().equals(HINT_TEXT) || this.label_title_tf.getText().trim().equals("")){
             JOptionPane.showMessageDialog(null,
                "Please title the label! \nFormat: Invoice, PO, Customer",
                "Invalid Title",
                JOptionPane.ERROR_MESSAGE);
             this.updateSavedState(false);
            return;
        }
        /*
         * step 1
         * Create document and set the page size. A6 is the closest thing to 4x6
         */
         
        Document document = new Document(PageSize.A6, 7.5f, 7.5f,0f,0f);
        /*
         * step 2
         * Create writer object and create the actual PDF file.
         */
        PdfWriter writer;
        String fileName = resolveFileName(".pdf");
        try{
            writer = PdfWriter.getInstance(document, new FileOutputStream(fileName));
        } catch (FileNotFoundException fnf) {
           boolean success = createFileDirectory();
            if (success) {
              writer = PdfWriter.getInstance(document, new FileOutputStream(fileName));
            } else {
                System.err.println("Unable to make directory");
                return;
            }
        }
      
        /*
         * step 3
         * Open the document by opening that actual PDF file
         */
        document.open();
        
        /*
         * step 4
         * Initialize table and barcode objects as well as other variables to be used
         */
        PdfContentByte cb = writer.getDirectContent();      //needed to convert a barcode to an image
        
        int caseNumber = 1;     //the current box number for the label; defaults to 1
        int numberOfCases = 1;  //the max number of boxes; defaults to 1
       
        
        
        PdfPTable table = initTable(3);     //init pdf table 
        
        PdfPCell cell = new PdfPCell();     //initalize cell object to dump the cell objects into
        cell.setFixedHeight(1f);            //set the max height of a cell table cell element
        cell.setPaddingTop(1f);             //set the padding at the top of the cell to help with spacing
        
        
        Barcode128 code128 = new Barcode128(); //init barcode object 
        code128.setSize(6f);                 //set barcode text size
        code128.setBarHeight(8);             //set the height of the bars
        code128.setX(.5f);                   //set the width of the bars
        int counter = 1;
        
        Integer unitsPerLabel;              //number of units to go on each label; physical limit is 20
        
        //try and parse the value out of the units per case field
        try{
             unitsPerLabel = Integer.parseInt(this.unitsPerCase_tf.getText());
             int test = unitsPerLabel + 1;
        } catch (Exception e){  //if an int couldn't be parsed then default unitsPerLabel to PACK_SIZE
            unitsPerLabel = PACK_SIZE;
        }
        
        //determine the number of boxes based on the number of serial numbers scanned in and units per box
        numberOfCases = (int)Math.ceil((float)getTableSize() / unitsPerLabel);
        if(numberOfCases <= 0){
            numberOfCases = 1;
        }
        
        
        addHeader(document, writer, caseNumber, numberOfCases); //add title and header to the document
        
        for(int i = 0; i < this.serialsTable.getRowCount(); i ++, counter++){
            try{
                Object obj_value = this.serialsTable.getValueAt(i, 1); //get the value of the current table row
                String value = obj_value.toString();                          //convert value to string
                
                //if for whatever reason the value is null or empty do nothing, decrement the counter and continue to the next row
                if(value == null || value.trim().equals("")){
                    counter--;
                    continue;
                } else {
                    boolean atLabelCapacity = (i % PACK_SIZE == 0 && i != 0);   //check to see if you're at the max units per label
                    boolean atBoxCapacity = (i % unitsPerLabel == 0 && i != 0); //check to see if you're at max units for a box
                    if(atBoxCapacity || atLabelCapacity) {                      //if you're at capacity you're going to need to make a newlabel
                        if((atLabelCapacity && atBoxCapacity) || atBoxCapacity){ //if you're at both capacities then increment case number
                                                                                 //of if you're just at box capacity increment case number
                            caseNumber++;
                        } 
                        document.add(table);                                    //add the current table to the document
                        document.newPage();                                     //create a new page
                        addHeader(document, writer, caseNumber, numberOfCases); //add header to the new page
                        table = initTable(3);                                   //initialize a new table object
                    }
                    
                    //create cell to hold current item number/iteration/count
                    cell = new PdfPCell(new Paragraph(""+counter, new Font(Font.FontFamily.HELVETICA, 6)));
                    cell.setBorder(0);              //remove cell border
                    cell.setPaddingTop(1f);         //pad the top of the cell a little for spacing
                    table.addCell(cell);            //add the cell to table
                    
                    code128.setCode(value.toUpperCase());    //set barcode code
                    
                    
                    if(value.length() > 40){            //if you're over 40 chars adjust the scale a bit
                        code128.setX(.4f);
                    }
                    
                    //create barcode image
                    com.itextpdf.text.Image tehImage = code128.createImageWithBarcode(cb, null, null); 
                    
                    cell = new PdfPCell(tehImage);  //add image data to cell object
                    cell.setBorder(0);              //remove cell border
                    cell.setPaddingTop(1f);         //set the top padding for spacing
                    table.addCell(cell);            //add the cell to the table
                }
            } catch(Exception e) {  //catch any exceptions and just press forward
                continue;
            }
        }
        
        
        document.add(table);  //finally add table to the document
        
        writer.setOpenAction(new PdfAction(PdfAction.PRINTDIALOG)); //make it so print dialog opens when pdf opens
        /*
         * step 5
         * Close the document
         */
        document.close();
        
        //save the data to .FILE_EXTENSION and .csv
        this.saveDataText();
        
        
        //open up adobe with the file you just made
        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File(fileName);
                Desktop.getDesktop().open(myFile);
            } catch (FileNotFoundException fnf){
                JOptionPane.showMessageDialog(null,
                    "Please close the PDF file before creating a new label!",
                    "File access error",
                    JOptionPane.ERROR_MESSAGE);
                this.updateSavedState(true);
                return;
            } catch (IOException ioe) {
                  JOptionPane.showMessageDialog(null,
                    "Error generating PDF file, please restart program and try again.",
                    "IO Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            } 
        }
    } catch (FileNotFoundException fnf){
                JOptionPane.showMessageDialog(null,
                "Please close the PDF file before creating a new label!",
                "File access error",
                JOptionPane.ERROR_MESSAGE);
            return;
    } catch (DocumentException de) {
            JOptionPane.showMessageDialog(null,
                "There was a problem generating the label, please create a new label and try again.",
                "Document error",
                JOptionPane.ERROR_MESSAGE);
            return;
    } 
}//GEN-LAST:event_printLabel_btnActionPerformed

/*
 * Function: newLabel_btnActionPerformed
 * Purpose: Clears all data fields so that a new label can be made
 * @param: ActionEvent evt
 */
private void newLabel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLabel_btnActionPerformed
    clear_btnActionPerformed(evt);          //call clear button to clear the serials table
     this.model_number_tf.setText(null);   //clear the model number field
     this.label_title_tf.setText(null);     //clear the title field
     this.unitsPerCase_tf.setText("20");    //reset units per case to 20
     focusTf();                             //set focus back to the title field
}//GEN-LAST:event_newLabel_btnActionPerformed


/*
 * Function: label_title_tfKeyPressed
 * Purpose: Redirects input to the model number/header field on a line return
 * @param: ActionEvent evt
 */
private void label_title_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_label_title_tfKeyPressed
    int keycode = evt.getKeyCode();
    if(keycode == 10){
        this.model_number_tf.requestFocusInWindow();
        this.model_number_tf.selectAll();
    }
    this.updateSavedState(false);
}//GEN-LAST:event_label_title_tfKeyPressed

/*
 * Function: header_number_tfKeyPressed
 * Purpose: Redirects input to the first row of the serials table on a line return
 * @param: ActionEvent evt
 */
private void model_number_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_model_number_tfKeyPressed
    int keycode = evt.getKeyCode();
    this.updateSavedState(true);
}//GEN-LAST:event_model_number_tfKeyPressed

/*
 * Function: print_menu_itemActionPerformed
 * Purpose: Calls the print label button action which handles the printing logic
 * @param ActionEvent evt 
 */
private void print_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_menu_itemActionPerformed
     printLabel_btnActionPerformed(evt);
}//GEN-LAST:event_print_menu_itemActionPerformed


/*
 * Function: formWindowOpened
 * Purpose: Initializes the custom cell editor for the serial numbers table, the file chooser for when
 * open file is called and the font used.
 * @param: WindowEvent evt
 */
private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //make sure the directory is created in order to open
        createFileDirectory();
        File openDirectory = new File(System.getProperty("user.home")+"\\Documents\\PackingLabels\\LabelFiles");
        jFileChooser1.setCurrentDirectory(openDirectory);
        FileFilter filter = new ExtensionFileFilter(".lbl, .csv", new String [] {"LBL", "CSV"});
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setFileFilter(filter);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
}//GEN-LAST:event_formWindowOpened

/*
 * Function: open_menuItemAction
 * Purpose: Opens the fileChooser and allows user to select a file from whatever directory they desire
 * @param ActionEvent evt
 */
private void open_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_menuItemActionPerformed
    int returnVal = this.jFileChooser1.showOpenDialog(this);
    if(returnVal == JFileChooser.APPROVE_OPTION) {
        newLabel_btnActionPerformed(evt);
        File file = this.jFileChooser1.getSelectedFile();
        String fileName = file.getName();
        String path = file.getAbsolutePath();
        System.out.println(path);
        loadLabel(path);
    }
}//GEN-LAST:event_open_menuItemActionPerformed

/*
 * Function: open_btnActionPerformed
 * Purpose: Calls the menu action for opening
 * @param ActionEvent evt
 */
private void open_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_btnActionPerformed
    open_menuItemActionPerformed(evt);
}//GEN-LAST:event_open_btnActionPerformed

/*
 * Function: newLabel_menuItemActionPerformed
 * Purpose: Calls the newlabel_btn action for clearing the fields
 * @param ActionEvent evt
 */
private void newLabel_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLabel_menuItemActionPerformed
    newLabel_btnActionPerformed(evt);
}//GEN-LAST:event_newLabel_menuItemActionPerformed

/*
 * Function: label_title_tfMouseClicked
 * Purpose: Selects all text data in the label title field when a click is done
 * @param: MouseEvent evt
 */
private void label_title_tfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_title_tfMouseClicked
    this.label_title_tf.selectAll();
}//GEN-LAST:event_label_title_tfMouseClicked

/*
 * Function: header_number_tfMouseClicked
 * Purpose: Selects all text data in the header number field when a click is done
 * @param: MouseEvent evt
 */
private void model_number_tfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_model_number_tfMouseClicked
    this.model_number_tf.selectAll();
}//GEN-LAST:event_model_number_tfMouseClicked

/*
 * Function: unitsPerCase_tfFocusLost
 * Purpose: Ensures that you can't exit the field and leave it empty; if you leave it empty
 * it fills with 20
 * @param: FocusEvent evt 
 */
private void unitsPerCase_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unitsPerCase_tfFocusLost
    if(this.unitsPerCase_tf.getText().trim().equals(""))
        this.unitsPerCase_tf.setText("20");
}//GEN-LAST:event_unitsPerCase_tfFocusLost

/*
 * Function: unitsPerCase_tfKeyReleased
 * Purpose: Ensures that you only type numbers into the units per case field; if you type in
 * a non numeric character it is removed. Could use some optimization.
 */
private void unitsPerCase_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitsPerCase_tfKeyReleased
    String text = unitsPerCase_tf.getText();
    String output = "";
    int replaced = -1;
    
    //ignore arrow keys
    switch(evt.getKeyCode()){
        case KeyEvent.VK_UP: return;
        case KeyEvent.VK_DOWN: return;
        case KeyEvent.VK_LEFT: return;
        case KeyEvent.VK_RIGHT: return;
    }
    char [] textArray = text.toCharArray();
    
    //loop through and check the text every time
    for(int i = 0; i < textArray.length; i++)
    {
        try{
            String input = ""+textArray[i];
            Integer tehInt = Integer.parseInt(input);
            int test = tehInt + 1;
            output += textArray[i];
        } catch (Exception e){
            textArray[i] = 'x';
            replaced = i;
        }
    }
    unitsPerCase_tf.setText(output);    //sets the text either to the fixed output or whatever value was entered
    if(replaced != -1)              //if something has been replaced put the caret back where it was
        unitsPerCase_tf.setCaretPosition(replaced);
    
}//GEN-LAST:event_unitsPerCase_tfKeyReleased

/*
 * Function: unitsPerCase_tfKeyPressed
 * Purpose: Focuses input on the serial numbers table when line return 
 * @param: KeyEvent evt
 */
private void unitsPerCase_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitsPerCase_tfKeyPressed
   int keycode = evt.getKeyCode();
    if(keycode == 10){
      
    }
}//GEN-LAST:event_unitsPerCase_tfKeyPressed

/*
 * Function: unitsPerCase_tfMouseClicked
 * Purpose: Selects all text in the units per box field on click
 */
private void unitsPerCase_tfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unitsPerCase_tfMouseClicked
    this.unitsPerCase_tf.selectAll();
}//GEN-LAST:event_unitsPerCase_tfMouseClicked

    private void serialEntry_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialEntry_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialEntry_tfActionPerformed

    private void serialAdd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialAdd_btnActionPerformed
        String temp = this.getSerial();
        if(temp == null || temp.trim().equals("")){
               JOptionPane.showMessageDialog(null,
                "Please enter a serial number",
                "Empty serial number error",
                JOptionPane.ERROR_MESSAGE);
        } else {
            this.addSerial();
        }
    }//GEN-LAST:event_serialAdd_btnActionPerformed

    private void serialEntry_tfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serialEntry_tfMouseClicked
        this.serialEntry_tf.selectAll();
    }//GEN-LAST:event_serialEntry_tfMouseClicked

    private void serialEntry_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialEntry_tfKeyPressed
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String temp = this.getSerial();
            if(temp == null || temp.trim().equals("")){
                   JOptionPane.showMessageDialog(null,
                    "Please enter a serial number",
                    "Empty serial number error",
                    JOptionPane.ERROR_MESSAGE);
            } else {
                this.addSerial();
            }
        }
    }//GEN-LAST:event_serialEntry_tfKeyPressed

    private void serialsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serialsTableMouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the entry?", "Confirm delete", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
          this.removeSerial(this.serialsTable.getSelectedRow());
        }
        else {
          return;
        }
    }//GEN-LAST:event_serialsTableMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("Not closing maang");
        if(!this.dataSaved){
            int reply = JOptionPane.showConfirmDialog(null, "Exit without saving/printing your current label?", "Unsaved data warning.", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                this.dispose();
                System.exit(0);
            }
            else {
                this.printLabel_btn.doClick();
            }
        } else {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing
    
    private boolean checkNewBox(){
        this.boxCount_lbl_data.setText(""+(this.serialCount) / this.getUnitsPerBox());
        boolean newBox = (this.serialCount) % this.getUnitsPerBox() == 0;
        
        if(this.serialCount == 0){
            this.boxCount_lbl_data.setText("0");
            return false;
        }
        if(newBox){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,
                "You completed a box!",
                "Box Complete",
                JOptionPane.WARNING_MESSAGE);
        }
        return (this.serialCount - 1) % this.getUnitsPerBox() == 0;
    }
    
    private int getUnitsPerBox(){
        String unitsPerBox = this.unitsPerCase_tf.getText();
        Integer upb = Integer.parseInt(unitsPerBox);
        return upb.intValue();
    }
    
    public boolean removeSerial(int index){
        int remRow = this.serialsTable.getSelectedRow();
        this.serialEntries.remove(index);
        DefaultTableModel model = (DefaultTableModel)this.serialsTable.getModel();
        model.removeRow(remRow);
        this.updateSerialCounter(-1);
        this.updateTableRows(remRow, model);
        
        
        return true; 
    }
    
    public void updateTableRows(int removedIndex, DefaultTableModel model){
        for(int i = removedIndex; i < this.serialCount; i++){
            int oldValue = (Integer)this.serialsTable.getValueAt(i, 0);
            if(oldValue < 0){ 
                oldValue = 0;
            }
            this.serialsTable.setValueAt(--oldValue, i, 0);
        }
    }
  
    
    public String getSerial(){
        return this.serialEntry_tf.getText();
    }
    
    public boolean checkSerial(){
        if(this.getSerial() == null || this.getSerial().trim().equals("")){
            return false;
        } else {
            return true;
        }
    }
    private boolean addSerial(){
        this.updateSavedState(false);
        if(checkSerial()){       
            DefaultTableModel model = (DefaultTableModel) this.serialsTable.getModel();
            model.addRow(new Object[]{this.serialCount+1,this.getSerial()});
            this.serialEntries.add(this.getSerial());
            this.updateSerialCounter(1);
            this.serialEntry_tf.setText(null);
            
            //scroll table to bottom
            this.serialsTable.scrollRectToVisible(this.serialsTable.getCellRect(this.serialsTable.getRowCount()-1, 0, true));
            
            return true;
        } else {
             JOptionPane.showMessageDialog(null,
                "No serial number entered. Please enter a serial number!",
                "No data error",
                JOptionPane.ERROR_MESSAGE);
             this.serialEntry_tf.setText(null);
             return false;
        }
    }
    
    private void updateSavedState(boolean state){
        this.dataSaved = state;
    }
    
    private boolean addSerial(String position, String serial){
            this.updateSavedState(false);
            DefaultTableModel model = (DefaultTableModel) this.serialsTable.getModel();
            model.addRow(new Object[]{Integer.parseInt(position),serial});
            this.serialEntries.add(serial);
            //this.updateSerialCounter(1);
            this.serialEntry_tf.setText(null);
            //scroll table to bottom
            this.serialsTable.scrollRectToVisible(this.serialsTable.getCellRect(this.serialsTable.getRowCount()-1, 0, true));
            return true;
    }
    
    public void updateSerialCounter(int update){
        this.serialCount += update;
        this.serialCount_lbl_data.setText(""+this.serialCount);
        this.checkNewBox();
        
    }
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GUI gui = new GUI();        //create an instance of a GUI
                BufferedImage image = null; //image object to hold favicon image
                
               try{                         //set the icon in the upper left corner
                   image = ImageIO.read(gui.getClass().getResource("unixfavicon.png")); 
                }
                catch(IOException e){
                    System.err.println("Error file not found");
                    e.printStackTrace();
                }
               gui.setIconImage(image);
               gui.focusTf();        //focus to the title field on program entry
               gui.setVisible(true); //set the gui visible
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boxCount_lbl_data;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel count_lbl;
    private javax.swing.JPanel display_panel;
    private javax.swing.JMenu file_menu;
    private javax.swing.JPanel footer_panel;
    private javax.swing.JLabel headerNumber_lbl;
    private javax.swing.JPanel header_panel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTitle_lbl;
    private javax.swing.JTextField label_title_tf;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField model_number_tf;
    private javax.swing.JButton newLabel_btn;
    private javax.swing.JMenuItem newLabel_menuItem;
    private javax.swing.JButton open_btn;
    private javax.swing.JMenuItem open_menuItem;
    private javax.swing.JButton printLabel_btn;
    private javax.swing.JMenuItem print_menu_item;
    private javax.swing.JButton serialAdd_btn;
    private javax.swing.JLabel serialCount_lbl_data;
    private javax.swing.JTextField serialEntry_tf;
    private javax.swing.JLabel serial_lbl;
    private javax.swing.JTable serialsTable;
    private javax.swing.JLabel unitsPerCase_lbl;
    private javax.swing.JTextField unitsPerCase_tf;
    // End of variables declaration//GEN-END:variables
    
}

